### ISSUE TITLE
Not able to detect when widget is shown

### ISSUE THREAD

**Issue by olaf89** [portis-project/web-sdk#25]
At the moment portis widget is loading for significant amount of time, I would like to show some loading indicator until widget is fully visible. I was hoping that portis.widget would resolve about that time, but there is significant delay after its resolved. Is there any way to hook into event of widget displayed to user?

**Comment by radotzki** [comment]
Hi @olaf89 👋 

Thanks for the feedback, we will check how we can reduce the load time of Portis Widget.

In the meanwhile, you can use that snippet in order to be notified when the Widget is ready:

```javascript
window.addEventListener(
  "message",
  e => {
    if (e.data && e.data.penpal && e.data.penpal === "handshake") {
      console.log("Widget is ready");
    }
  },
  false
);
```

You can see a live example here:
https://codesandbox.io/s/widget-is-ready-4qgx6

Let me know if it works 😃

**Comment by olaf89** [comment]
Thanks for quick answer, 

the callback that you provided is being executed before portis.widget is resolved.I am observing still a delay after its called and before widget is really visible to the user.

**Comment by radotzki** [comment]
That a little bit hacky, but it works better 😅

```javascript
web3.eth.net.getId().then(() => {
  console.log("Widget is ready");
});
```

**Comment by olaf89** [comment]
It works, thanks.
