### ISSUE TITLE
Provider doesn't respond to net_version call immediately after  onLogin

### ISSUE THREAD

**Issue by cloudonshore** [portis-project/web-sdk#9]
To replicate, you can simply run the following code:
```
portis.onLogin(() => {
    window.setInterval(
      () =>
        console.log(
          portis.provider.send({ method: 'net_version' }),
        ),
      100,
    )
  })
```
For me, it returns the following output: 
<img width="705" alt="Screen Shot 2019-04-11 at 3 34 27 PM" src="https://user-images.githubusercontent.com/1197232/55987783-4679f100-5c70-11e9-9087-553a9905fe71.png">

I think expected behavior would be the "onLogin" wouldn't return until all JSON RPC calls were ready. This was causing a race condition in my code (since wallets all store their "current network" on their web3 providers slightly differently, I've found using the JSON RPC call to be the most standardized way of accessing this information).

Thanks!
Sam Walker

**Comment by radotzki** [comment]
Thanks for this feedback, Sam.
We'll look into it and update you soon.

**Comment by radotzki** [comment]
@cloudonshore after several inner debates we decided that this is the correct behavior and we will not change it, for several reasons:
1. As a best practice, developers should always use the async version of `get network` (`web3.eth.net.getId()`).
2. There may be use cases where developers will want to get the response from `onLogin` and the network is not relevant for them. In those cases, we will degrade the response speed because we will wait for the network id from the endpoint.

Hope you understand our decision, and of course, we are happy to help anytime you need :)
